# Generated by Django 5.0.3 on 2024-05-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('NON IT', 'NON IT')], max_length=23, null=True)),
                ('name', models.CharField(blank=True, max_length=23, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_student', to='app1.student')),
            ],
        ),
    ]
